varying highp vec4 xlv_COLOR1;
varying highp vec4 xlv_TEXCOORD2;
varying highp vec4 xlv_COLOR0;
varying highp vec4 xlv_TEXCOORD0;
uniform sampler2D DiffuseMap;
uniform sampler2D LightMapLookup;
uniform sampler2D LightMap;
uniform highp vec4 LightBorder;
uniform highp vec4 LightConfig3;
uniform highp vec4 LightConfig2;
uniform highp vec3 FogColor;
uniform highp vec3 AmbientColor;
uniform highp vec3 Lamp0Color;
void main ()
{
  highp vec4 oColor0_1;
  lowp vec4 tmpvar_2;
  tmpvar_2 = texture2D (DiffuseMap, xlv_TEXCOORD0.xy);
  highp vec4 tmpvar_3;
  tmpvar_3 = (tmpvar_2 * xlv_COLOR0);
  highp vec3 tmpvar_4;
  tmpvar_4 = abs((xlv_TEXCOORD2.xyz - LightConfig2.xyz));
  highp vec3 t_5;
  t_5.x = float((tmpvar_4.x >= LightConfig3.x));
  t_5.y = float((tmpvar_4.y >= LightConfig3.y));
  t_5.z = float((tmpvar_4.z >= LightConfig3.z));
  highp float tmpvar_6;
  tmpvar_6 = min (dot (t_5, vec3(1.0, 1.0, 1.0)), 1.0);
  highp vec4 s1_7;
  highp vec4 s0_8;
  highp vec4 offsets_9;
  lowp vec4 tmpvar_10;
  tmpvar_10 = texture2D (LightMapLookup, xlv_TEXCOORD2.xy);
  offsets_9 = tmpvar_10;
  highp vec2 tmpvar_11;
  tmpvar_11 = (xlv_TEXCOORD2.yz * 0.125);
  highp vec2 tmpvar_12;
  tmpvar_12 = (tmpvar_11 - (tmpvar_11 * tmpvar_6));
  lowp vec4 tmpvar_13;
  highp vec2 P_14;
  P_14 = (tmpvar_12 + offsets_9.xy);
  tmpvar_13 = texture2D (LightMap, P_14);
  s0_8 = tmpvar_13;
  lowp vec4 tmpvar_15;
  highp vec2 P_16;
  P_16 = (tmpvar_12 + offsets_9.zw);
  tmpvar_15 = texture2D (LightMap, P_16);
  s1_7 = tmpvar_15;
  highp vec4 tmpvar_17;
  tmpvar_17 = mix (mix (s0_8, s1_7, vec4(fract((xlv_TEXCOORD2.x * 64.0)))), LightBorder, vec4(tmpvar_6));
  oColor0_1.xyz = ((((AmbientColor + (xlv_COLOR1.xyz * tmpvar_17.w)) + tmpvar_17.xyz) * tmpvar_3.xyz) + (Lamp0Color * (xlv_COLOR1.w * tmpvar_17.w)));
  oColor0_1.w = tmpvar_3.w;
  oColor0_1.xyz = mix (FogColor, oColor0_1.xyz, vec3(clamp (xlv_TEXCOORD2.w, 0.0, 1.0)));
  gl_FragData[0] = oColor0_1;
}

